//show alert
export const DISPLAY_ALERT = "DISPLAY_ALERT";
//clear alert
export const CLEAR_ALERT = "CLEAR_ALERT";
//register user
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
//login user
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
//toggle sidebar
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
//logout user
export const LOGOUT_USER = "LOGOUT_USER";
//update user
export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
//get all users
export const GET_ALL_USERS_BEGIN = "GET_ALL_USERS_BEGIN";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
//set update user
export const SET_UPDATE_USER = "SET_UPDATE_USER";
//update user admin
export const UPDATE_USER_ADMIN_BEGIN = "UPDATE_USER_ADMIN_BEGIN";
export const UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS";
export const UPDATE_USER_ADMIN_ERROR = "UPDATE_USER_ADMIN_ERROR";
//set delete user
export const SET_DELETE_USER = "SET_DELETE_USER";
//delete user
export const DELETE_USER = "DELETE_USER";

//supervise
export const SUPERVISE_BEGIN = "SUPERVISE_BEGIN";
export const SUPERVISE_SUCCESS = "SUPERVISE_SUCCESS";
export const SUPERVISE_ERROR = "SUPERVISE_ERROR";

//student group reg
export const STUDENT_GROUP_BEGIN = "STUDENT_GROUP_BEGIN";
export const STUDENT_GROUP_SUCCESS = "STUDENT_GROUP_SUCCESS";
export const STUDENT_GROUP_ERROR = "STUDENT_GROUP_ERROR";

//get Student Group Register Details
export const GET_STUDENT_GROUP_BEGIN = "GET_STUDENT_GROUP_BEGIN";
export const GET_STUDENT_GROUP_SUCCESS = "GET_STUDENT_GROUP_SUCCESS";
export const GET_STUDENT_GROUP_ERROR = "GET_STUDENT_GROUP_ERROR";

//get all Student Groups

export const GET_ALL_STUDENT_GROUPS_BEGIN = "GET_ALL_STUDENT_GROUPS_BEGIN";
export const GET_ALL_STUDENT_GROUPS_SUCCESS = "GET_ALL_STUDENT_GROUPS_SUCCESS";
export const GET_ALL_STUDENT_GROUPS_END = "GET_ALL_STUDENT_GROUPS_END";

//get all submissions
export const GET_ALL_SUBMISSIONS_BEGIN = "GET_ALL_SUBMISSIONS_BEGIN";
export const GET_ALL_SUBMISSIONS_SUCCESS = "GET_ALL_SUBMISSIONS_SUCCESS";

//create a submission
export const CREATE_A_SUBMISSION_BEGIN = "CREATE_A_SUBMISSION_BEGIN";
export const CREATE_A_SUBMISSION_SUCCESS = "CREATE_A_SUBMISSION_SUCCESS";
export const CREATE_A_SUBMISSION_END = "CREATE_A_SUBMISSION_END";

//delete a submission
export const DELETE_A_SUBMISSION = "CREATE_A_SUBMISSION_END";

//view supervisor
export const SET_VIEW_SUPERVISOR = "SET_VIEW_SUPERVISOR";


