//show alert
export const DISPLAY_ALERT = "DISPLAY_ALERT";
//clear alert
export const CLEAR_ALERT = "CLEAR_ALERT";
//register user
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
//login user
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
//toggle sidebar
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
//logout user
export const LOGOUT_USER = "LOGOUT_USER";
//update user
export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
//get all users
export const GET_ALL_USERS_BEGIN = "GET_ALL_USERS_BEGIN";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
//set update user
export const SET_UPDATE_USER = "SET_UPDATE_USER";
//update user admin
export const UPDATE_USER_ADMIN_BEGIN = "UPDATE_USER_ADMIN_BEGIN";
export const UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS";
export const UPDATE_USER_ADMIN_ERROR = "UPDATE_USER_ADMIN_ERROR";
//set delete user
export const SET_DELETE_USER = "SET_DELETE_USER";
//delete user
export const DELETE_USER = "DELETE_USER";

//supervise
export const SUPERVISE_BEGIN = "SUPERVISE_BEGIN";
export const SUPERVISE_SUCCESS = "SUPERVISE_SUCCESS";
export const SUPERVISE_ERROR = "SUPERVISE_ERROR";

//get specific supervise(supervisor dashboard)
export const GET_SUPERVISE_BEGIN = "GET_SUPERVISE_BEGIN";
export const GET_SUPERVISE_SUCCESS = "GET_SUPERVISE_SUCCESS";
export const GET_SUPERVISE_ERROR = "GET_SUPERVISE_ERROR";

//delete specific supervisor
export const DELETE_SUPERVISE_BEGIN = "DELETE_SUPERVISE_BEGIN";
export const DELETE_SUPERVISE_SUCCESS = "DELETE_SUPERVISE_SUCCESS";
export const DELETE_SUPERVISE_ERROR = "DELETE_SUPERVISE_ERROR";

//update specific supervisor
export const SET_UPDATE_SUPERVISE = "SET_UPDATE_SUPERVISE";
export const UPDATE_SUPERVISE_BEGIN = "UPDATE_SUPERVISE_BEGIN";
export const UPDATE_SUPERVISE_SUCCESS = "UPDATE_SUPERVISE_SUCCESS";
export const UPDATE_SUPERVISE_ERROR = "UPDATE_SUPERVISE_ERROR";

//student group reg
export const STUDENT_GROUP_BEGIN = "STUDENT_GROUP_BEGIN";
export const STUDENT_GROUP_SUCCESS = "STUDENT_GROUP_SUCCESS";
export const STUDENT_GROUP_ERROR = "STUDENT_GROUP_ERROR";

//get Student Group Register Details
export const GET_STUDENT_GROUP_BEGIN = "GET_STUDENT_GROUP_BEGIN";
export const GET_STUDENT_GROUP_SUCCESS = "GET_STUDENT_GROUP_SUCCESS";
export const GET_STUDENT_GROUP_ERROR = "GET_STUDENT_GROUP_ERROR";

//get all Student Groups

export const GET_ALL_STUDENT_GROUPS_BEGIN = "GET_ALL_STUDENT_GROUPS_BEGIN";
export const GET_ALL_STUDENT_GROUPS_SUCCESS = "GET_ALL_STUDENT_GROUPS_SUCCESS";
export const GET_ALL_STUDENT_GROUPS_END = "GET_ALL_STUDENT_GROUPS_END";

//get all submissions
export const GET_ALL_SUBMISSIONS_BEGIN = "GET_ALL_SUBMISSIONS_BEGIN";
export const GET_ALL_SUBMISSIONS_SUCCESS = "GET_ALL_SUBMISSIONS_SUCCESS";

//create a submission
export const CREATE_A_SUBMISSION_BEGIN = "CREATE_A_SUBMISSION_BEGIN";
export const CREATE_A_SUBMISSION_SUCCESS = "CREATE_A_SUBMISSION_SUCCESS";
export const CREATE_A_SUBMISSION_END = "CREATE_A_SUBMISSION_END";

//get all supervisor
export const GET_ALL_SUPERVISORS_BEGIN = "GET_ALL_SUPERVISORS_BEGIN";
export const GET_ALL_SUPERVISORS_SUCCESS = "GET_ALL_SUPERVISORS_SUCCESS";
export const GET_ALL_SUPERVISORS_ERROR = "GET_ALL_SUPERVISORS_ERROR";

//post supervisor request from student
export const GET_SUPERVISOR_REQUEST_BEGIN = "GET_SUPERVISOR_REQUEST_BEGIN";
export const GET_SUPERVISOR_REQUEST_SUCCESS = "GET_SUPERVISOR_REQUEST_SUCCESS";
export const GET_SUPERVISOR_REQUEST_ERROR = "GET_SUPERVISOR_REQUEST_ERROR";

//get core supervisors
export const GET_ALL_COSUPERVISORS_BEGIN = "GET_ALL_COSUPERVISORS_BEGIN";
export const GET_ALL_COSUPERVISORS_SUCCESS = "GET_ALL_COSUPERVISORS_SUCCESS";

export const STUDENT_REQUEST_STATUS = "STUDENT_REQUEST_STATUS";

export const GET_COSUPERVISOR_REQUEST_BEGIN = "GET_COSUPERVISOR_REQUEST_BEGIN";
export const GET_COSUPERVISOR_REQUEST_SUCCESS =
  "GET_COSUPERVISOR_REQUEST_SUCCESS";
export const GET_COSUPERVISOR_REQUEST_ERROR = "GET_COSUPERVISOR_REQUEST_ERROR";

//get supervisor request  from student
export const STUDENT_SUPERVISOR_REQUEST_BEGIN =
  "STUDENT_SUPERVISOR_REQUEST_BEGIN";
export const STUDENT_SUPERVISOR_REQUEST_SUCCESS =
  "STUDENT_SUPERVISOR_REQUEST_SUCCESS";
export const STUDENT_SUPERVISOR_REQUEST_ERROR =
  "STUDENT_SUPERVISOR_REQUEST_ERROR";

//student edit topic in supervisor request
export const STUDENT_SUPERVISOR_EDIT_TOPIC_BEGIN =
  "STUDENT_SUPERVISOR_EDIT_TOPIC_BEGIN";
export const STUDENT_SUPERVISOR_EDIT_TOPIC_SUCCESS =
  "STUDENT_SUPERVISOR_EDIT_TOPIC_SUCCESS";
export const STUDENT_SUPERVISOR_EDIT_TOPIC_ERROR =
  "STUDENT_SUPERVISOR_EDIT_TOPIC_ERROR";

//co-supervisor group details
export const STUDENT_COSUPERVISOR_REQUEST_SUCCESS =
  "STUDENT_COSUPERVISOR_REQUEST_SUCCESS";

//delete a submission
export const DELETE_A_SUBMISSION = "CREATE_A_SUBMISSION_END";

//view supervisor
export const SET_VIEW_SUPERVISOR = "SET_VIEW_SUPERVISOR";

//display success upload alert
export const DISPLAY_UPLOAD_SUCCESS_ALERT = "DISPLAY_UPLOAD_SUCCESS_ALERT";

//student request in supervisor
export const REQUEST_FOR_SUPERVISOR_SUCCESS = "REQUEST_FOR_SUPERVISOR_SUCCESS";

// supervisor accept request
export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const ACCEPT_REQUEST_ERROR = "ACCEPT_REQUEST_ERROR";
export const DECLINED_REQUEST_SUCCESS = "DECLINED_REQUEST_SUCCESS";
export const GET_SUPERVISOR_GROUP_BEGIN = "GET_SUPERVISOR_GROUP_BEGIN";
export const GET_SUPERVISOR_GROUP_SUCCESS = "GET_SUPERVISOR_GROUP_SUCCESS";

//handle change
export const HANDLE_CHANGE = "HANDLE_CHANGE";

//clear filter
export const CLEAR_FILTER = "CLEAR_FILTER";

//messages
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";

//panel member
export const GET_EVALUATION_GROUP_BEGIN = "GET_EVALUATION_GROUP_BEGIN";
export const GET_EVALUATION_GROUP_SUCCESS = "GET_EVALUATION_GROUP_SUCCESS";

export const UPDATE_PANEL_ADMIN_ERROR = "UPDATE_PANEL_ADMIN_ERROR";
export const UPDATE_PANEL_ADMIN_SUCCESS = "UPDATE_PANEL_ADMIN_SUCCESS";
export const UPDATE_PANEL_ADMIN_BEGIN = "UPDATE_PANEL_ADMIN_BEGIN";

//clear filter Student
export const CLEAR_FILTER_STUDENT = "CLEAR_FILTER_STUDENT";

//clear filter StudentSupervisor
export const CLEAR_FILTER_STUDENTSUPERVISOR = "CLEAR_FILTER_STUDENTSUPERVISOR";
